# H2 in-memory datasource
spring.datasource.url=jdbc:h2:mem:kitchensink;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# Keep explicit names when specified on annotations
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Web
server.error.include-message=never

# H2 console (optional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
