-- Sample data for kitchensink-spring-boot application
-- This SQL script is automatically executed by Spring Boot when the application starts
-- It populates the database with initial test data

-- Insert a sample member (ID will be auto-generated by Spring Boot)
INSERT INTO Member (name, email, phone_number) 
VALUES ('John Smith', 'john.smith@mailinator.com', '2125551212');
